# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SheptherdTone
subtitle: film production and media services
email: office@shepherdtone.co.uk
description: >- # this means to ignore newlines until "baseurl:"
    film production and media services in London
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.shepherdtone.co.uk" # the base hostname & protocol for your site, e.g. http://example.com

#instagram: andreisas_dop
#vimeo: andreisas
#linkedin: andrei-sas
#twitter: andreisas_dop


# Build settings
theme: minima

# Collections
# won't generate individual pages but will grab data for each collection item
collections_dir: portfolio
collections:
  narrative:
    title: Narrative Film
    order: 1
    output: false
    text: "Film is perhaps the most engaging form of visual storytelling. The end goal is to captivate the audience and produce inspiring artefacts of the human condition."
  music:
    title: Music Videos
    order: 2
    output: false
    text: "The music video is a lynchpin to the modern musician. Nowadays more talent is being discovered through video streaming platforms than any other means. Our aim is to create the best possible visuals that complement your music."
  editorial:
    title: Editorial
    order: 3
    output: false
    text: "We live in a world where artists and entrepreneurs can address their target audience directly and as such digital content comes in varied formats that steer away from traditional media."
  promo:
    title: Adverts & Branded Content
    order: 4
    output: false
    text: "The best way to get your demographic talking is to ask a question and have the answear lead to you. To this end, promotional videos are evolving into true narratives in their own right, becoming more than marketing tools."
  corporate:
    title: Corporate & Education
    order: 5
    output: false
    text: "When promoting a new business, or documenting an important event, a press release just isn’t enough anymore. Using online video as a tool to this end is an important part of what we do."
  live:
    title: Live Sessions
    order: 6
    output: false
    text: "Sometimes it’s hard to gauge a performer by listening to their radio singles. Live sessions take the veil off and allow the audience to get to know you in an intimate, personal video."
  photography:
    title: Photography
    order: 7
    output: false
